version: '3.8'

services:
  keycloak:
    image: jboss/keycloak:10.0.0
    container_name: keycloak
    restart: always
    volumes:
      - ./realm-config:/opt/jboss/keycloak/realm-config
    environment:
      DB_VENDOR: h2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 9080:8080
      - 9443:9443
      - 10990:10990

